version: '3'
volumes:
  kong_data: {}
networks:
  kong-net:
services:
  kong:
    build: .
    user: kong
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_LOG_LEVEL: debug
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PLUGINS: bundled,ecies-encrypt
      KONG_PLUGINSERVER_NAMES: ecies-encrypt
      KONG_PLUGINSERVER_ECIES_ENCRYPT_START_CMD: /usr/local/bin/ecies-encrypt
      KONG_PLUGINSERVER_ECIES_ENCRYPT_QUERY_CMD: /usr/local/bin/ecies-encrypt -dump
    networks:
      - kong-net
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
      - "8002:8002/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
